# Setup
title: kkmonster
description:  生命中有万事的可能
url:  https://kunmonster.github.io/
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
# Optimize Jekyll
exclude:
#  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
social:
  name: Feng kunjiang
  links:
    - https://github.com/kunmonster
google_site_verification: xxxxx
lang: en


destination:  docs

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Feng kunjiang
  url: https://github.com/kunmonster/
  email: fkj_monster@163.com
